=== JRamSan0607/LMSGI_UD4/XML/Concesionario/AlmCoches.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    version="0.1" xml:lang="es">
    <xs:element name="AlmacenamientoCoches">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="coche" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigoDeCoche" type="xs:string"/>
                            <xs:element name="marca" type="xs:string"/>
                            <xs:element name="modelo" type="xs:string"/>
                            <xs:element name="matricula" type="xs:string"/>
                            <xs:element name="potencia" type="xs:string"/>
                            <xs:element name="plazas" type="xs:string"/>
                            <xs:element name="puertas" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JRamSan0607/LMSGI_UD4/XML/Concesionario/AlmacenamientoCoches-X.xml
<?xml version="1.0" encoding="utf-8"?>
<AlmacenamientoCoches xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="AlmCoches.xsd">
    <coche>
        <codigoDeCoche>P67H23B</codigoDeCoche>
        <marca>Skoda</marca>
        <modelo>Fabia Injection</modelo>
        <matricula>67455CBJ</matricula>
        <potencia>75CV</potencia>
        <plazas>5</plazas>
        <puertas>5</puertas>
    </coche>
    <coche>
        <codigoDeCoche>I45V64R</codigoDeCoche>
        <marca>Seat</marca>
        <modelo>Leon ST 2.0 TDI</modelo>
        <matricula>76492HJW</matricula>
        <potencia>150CV</potencia>
        <plazas>5</plazas>
        <puertas>5</puertas>
    </coche>
    <coche>
        <codigoDeCoche>J78Y54L</codigoDeCoche>
        <marca>Kia</marca>
        <modelo>Ceed 1.0 MHEV</modelo>
        <matricula>78392WJT</matricula>
        <potencia>120CV</potencia>
        <plazas>5</plazas>
        <puertas>5</puertas>
    </coche>
    <coche>
        <codigoDeCoche>H67W28E</codigoDeCoche>
        <marca>Volkswagen</marca>
        <modelo>Polo A-Polo Plus 1.2 TSI</modelo>
        <matricula>67485HBY</matricula>
        <potencia>90CV</potencia>
        <plazas>5</plazas>
        <puertas>5</puertas>
    </coche>
    <coche>
        <codigoDeCoche>B57D30A</codigoDeCoche>
        <marca>BMW</marca>
        <modelo>X5 xDrive30d</modelo>
        <matricula>67401WIF</matricula>
        <potencia>258CV</potencia>
        <plazas>5</plazas>
        <puertas>5</puertas>
    </coche>
</AlmacenamientoCoches>
